### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by EMTuckerLab** [scan-bugs-org/iDigBees#12]
Get rid of "Nature Loves Bees" and re-write section to be more relevant as previously discussed with Neil...

**Comment by neilcobb** [comment]
Hooray!

Neil S. Cobb,

Biodiversity Outreach Network <https://www.bon-earth.org/>  Flagstaff AZ
*Business Office: *285 W Rome Way, Paulden, AZ86334; *Operations Office: *11
W Silver Spruce Ave, Flagstaff, AZ  86001

Summer Bug Camps <https://www.bon-earth.org/bugcamp>

SCAN <https://scan-bugs.org/portal/index.php>  North American Arthropod
Portal

iDigBees TCN <https://idigbees.org/>

Mobile Office - Text & WhatsApp: 928-607-4075

Zoom Office:  *https://us02web.zoom.us/j/81630476460
<https://us02web.zoom.us/j/81630476460>*

ORCID  https://orcid.org/0000-0002-6155-9444

**Comment by EMTuckerLab** [comment]
Updated the about page. Included a brief blurb on how all the different projects fit together. Feel free to edit what I wrote (see https://idigbees.org/about/).
