### ISSUE TITLE
Twitter feed down?

### ISSUE THREAD

**Issue by EMTuckerLab** [scan-bugs-org/iDigBees#15]
The twitter feed on the News page appears to have stopped working. @EMTuckerLab - try to figure out why and fix it!

**Comment by neilcobb** [comment]
thanks, the twitter account is working fine on twitter.


Neil S. Cobb,

Biodiversity Outreach Network <https://www.bon-earth.org/>  Flagstaff AZ
*Business Office: *285 W Rome Way, Paulden, AZ86334; *Operations Office: *11
W Silver Spruce Ave, Flagstaff, AZ  86001

Summer Bug Camps <https://www.bon-earth.org/bugcamp>

SCAN <https://scan-bugs.org/portal/index.php>  North American Arthropod
Portal

iDigBees TCN <https://idigbees.org/>

Mobile Office - Text & WhatsApp: 928-607-4075

Zoom Office:  *https://us02web.zoom.us/j/81630476460
<https://us02web.zoom.us/j/81630476460>*

ORCID  https://orcid.org/0000-0002-6155-9444

**Comment by EMTuckerLab** [comment]
Yeah - I checked that. It's something on the website side. I'll look into
it...

----------
Erika Tucker, PhD (s*he/her/hers*)
Milwaukee Public Museum <https://www.mpm.edu/> (MPM) | Community Engagement
Projects Manager
Biodiversity Outreach Network <https://www.bon-earth.org/> (BON) | iDigBees
<http://idigbees.org/> | Terrestrial Parasite Tracker
<https://bit.ly/TPTiDigBio> (TPT)
ORCiD 0000-0002-8822-2315 <https://orcid.org/0000-0002-8822-2315>
*Entomologist & Museum Collection Specialist*

Check it out!
   *Bug.News <http://bug.news/> *(blog)
   iDigBees Resources <https://idigbees.org/resources/>
   TPT Resources & Products
<https://www.idigbio.org/wiki/index.php/Digitizing_collections_to_trace_parasite-host_associations_and_predict_the_spread_of_vector-borne_disease>
   BON Entomological Resources
<https://www.bon-earth.org/products-resources> (supplies, DIY, etc.)
   BugFlow <https://entcollnet.github.io/BugFlow/> (digitization workflows)
   GloBI How-To <https://www.globalbioticinteractions.org/how-to> (help
page)
   *Bug Jewelry* <https://www.earthengypsydesigns.com/category/bugs> (made
with real bugs)

**Comment by EMTuckerLab** [comment]
Well - it seems to have resolved itself. Its now showing the feed just fine. Not sure what happened, but will try and check more frequently to make sure still functioning properly.
