### ISSUE TITLE
Add Google Analytics for website

### ISSUE THREAD

**Issue by EMTuckerLab** [scan-bugs-org/iDigBees#16]
Add google analytics to website and make it so all admins/editor can access (i.e., Neil, Anne, Erika).

**Comment by EMTuckerLab** [comment]
Shouldn't be that hard to do, but the plugins for word press keep failing. Tried updating the other plugins for the site, including elementor, as many are marked as out of date in case this was causing the issues. Plus the website has been a bit slow loading pages. The plugins should update automatically, so not sure what's up with that. 
None of the out of date plugin seem to be able to update - either automatically, or when I manually click the button. I'm guessing this is all tied in with not being able to install a new plug in.

**Comment by EMTuckerLab** [comment]
Contacted the help desk for BlueHost to see if they can look into the failed plugin additions and the failed plug in updates. They need me to generate a "token" for security reasons from this link: https://my.bluehost.com/cgi/dm 
Apparently, this is not the same login as for the main iDigBees wordpress...

**Comment by EMTuckerLab** [comment]
Talked to Neil. Got passwords reset and now Erika has access to wordpress main site. Help desk resolved the plugin update issues. We now have google analytics installed :)

**Comment by EMTuckerLab** [comment]
I believe it takes about 48 hours to start collecting data. If no data by Mon/Tue we can reopen the issue.

**Comment by neilcobb** [comment]
I do not have BON website listed in Google Analytics, maybe go over this in next Thursday'ss meeting
