### ISSUE TITLE
Please add more graphics to SmartBee page

### ISSUE THREAD

**Issue by EMTuckerLab** [scan-bugs-org/iDigBees#19]
Need to add more of the cool graphics and images that Anne has to the SmartBee page (https://idigbees.org/smartbee/). 
Also, update text content so that it's different from the main education page?

**Comment by neilcobb** [comment]
Every time I think of a native bee graphic I think of this great little
book, and there are others, like bees in your backyard for the more adult
and serious natural history types.  Can we not promote these on our
education pages?  then there are the native plant/pollinator resources that
spill over to citizen science restoration.

[image: image.png]

Neil S. Cobb,

Biodiversity Outreach Network <https://www.bon-earth.org/>  Flagstaff AZ
*Business Office: *285 W Rome Way, Paulden, AZ86334; *Operations Office: *11
W Silver Spruce Ave, Flagstaff, AZ  86001

Summer Bug Camps <https://www.bon-earth.org/bugcamp>

SCAN <https://scan-bugs.org/portal/index.php>  North American Arthropod
Portal

iDigBees TCN <https://idigbees.org/>

Mobile Office - Text & WhatsApp: 928-607-4075

Zoom Office:  *https://us02web.zoom.us/j/81630476460
<https://us02web.zoom.us/j/81630476460>*

ORCID  https://orcid.org/0000-0002-6155-9444

**Comment by EarthTeach** [comment]
Yes, they can certainly be featured under a category like "recommended resources" but should not be featured in a way to suggest it is one of our own publications or as a project of iDigbees.   You can also feature books on BON and even sell them (which I was trying to set up) but it would likely require permission and an agreement from the publisher to be set up as a distributor.

**Comment by neilcobb** [comment]
I just want to let people know about good books.


Neil S. Cobb,

Biodiversity Outreach Network <https://www.bon-earth.org/>  Flagstaff AZ
*Business Office: *285 W Rome Way, Paulden, AZ86334; *Operations Office: *11
W Silver Spruce Ave, Flagstaff, AZ  86001

Summer Bug Camps <https://www.bon-earth.org/bugcamp>

SCAN <https://scan-bugs.org/portal/index.php>  North American Arthropod
Portal

iDigBees TCN <https://idigbees.org/>

Mobile Office - Text & WhatsApp: 928-607-4075

Zoom Office:  *https://us02web.zoom.us/j/81630476460
<https://us02web.zoom.us/j/81630476460>*

ORCID  https://orcid.org/0000-0002-6155-9444

**Comment by EarthTeach** [comment]
Yes--We can start compiling links to recommended resources---then add to main education page.

**Comment by EarthTeach** [comment]
The SmartBee page should only feature graphics that are related to SmartBee products--- graphics of the learning mats as they are completed will be posted there.  For now I can add visuals related to the research aspect of the project.

**Comment by neilcobb** [comment]
Yep


Neil S. Cobb,

Biodiversity Outreach Network <https://www.bon-earth.org/>  Flagstaff AZ
*Business Office: *285 W Rome Way, Paulden, AZ86334; *Operations Office: *11
W Silver Spruce Ave, Flagstaff, AZ  86001

Summer Bug Camps <https://www.bon-earth.org/bugcamp>

SCAN <https://scan-bugs.org/portal/index.php>  North American Arthropod
Portal

iDigBees TCN <https://idigbees.org/>

Mobile Office - Text & WhatsApp: 928-607-4075

Zoom Office:  *https://us02web.zoom.us/j/81630476460
<https://us02web.zoom.us/j/81630476460>*

ORCID  https://orcid.org/0000-0002-6155-9444

**Comment by EarthTeach** [comment]
Content added for Education page and Smart Bee page.
