### ISSUE TITLE
iNat Project setup for FLAAR/Guatemala group 

### ISSUE THREAD

**Issue by EMTuckerLab** [scan-bugs-org/iDigBees#8]
Need to find out if FLAAR is going to be able to set up the iNat project page, or if Erika/Anne should just do it for them. 
Needs to be done ASAP before the next field excursion since not currently able to collect physical specimens. 
@anne@bon-earth.org & Erika

**Comment by EMTuckerLab** [comment]
Erika emailed group... Anne replied that she thought Vivian wanted to create it... Now waiting on FLAAR to say one way or another

**Comment by neilcobb** [comment]
well we have done everything we can....thanks

Neil S. Cobb,

Biodiversity Outreach Network <https://www.bon-earth.org/>  Flagstaff AZ
*Business Office: *285 W Rome Way, Paulden, Az   86334
*Operations Office: *11 W Silver Spruce Ave, Flagstaff, AZ   86001


SCAN <https://scan-bugs.org/portal/index.php>  North American Arthropod
Portal

iDigBees TCN <https://idigbees.org/>

Mobile Office: 928-607-4075

Virtual Office:  *https://us02web.zoom.us/j/81630476460
<https://us02web.zoom.us/j/81630476460>*

ORCID  https://orcid.org/0000-0002-6155-9444

**Comment by EMTuckerLab** [comment]
done: https://www.inaturalist.org/projects/guatemalan-bee-project
